### ISSUE TITLE
Our Company page: Border bottom is not necessary for the last post

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#143]
![2016-05-23_1420](https://cloud.githubusercontent.com/assets/13309806/15465332/9d9e67d0-20f1-11e6-8dc2-c8e004bf741c.png)

**Comment by euveng** [comment]
Fixed.

**Comment by ravi-josyula** [comment]
Since it is not fixed
I mentioned it for only last post but not for all posts
Please refer the following screenshot or psd once
![2016-06-03_1408](https://cloud.githubusercontent.com/assets/13309806/15773486/bc54e0d6-2994-11e6-8515-96e97fe4363d.png)

**Comment by euveng** [comment]
Fixed.
