### ISSUE TITLE
Admin(Menu) : Menu should be styled as per the design

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#17]
![2](https://cloud.githubusercontent.com/assets/13309806/14781657/6fd4adc4-0b01-11e6-8b6e-bff8776b3633.png)

**Comment by adrian-chan-titan** [comment]
styled for 2 levels

**Comment by euveng** [comment]
Fixed.

**Comment by ravi-josyula** [comment]
Still issue is not fixed
Second level menu should be equal with first level menu

![2016-06-03_1613](https://cloud.githubusercontent.com/assets/13309806/15776618/a23dfa54-29a6-11e6-9f36-ef3616935bd2.png)

**Comment by euveng** [comment]
Fixed.
