### ISSUE TITLE
Our Company Page : Limit the title to one line

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#62]
![our company - cse global 2016-04-26 10-12-31](https://cloud.githubusercontent.com/assets/13309806/14811953/81fe1aa0-0bb8-11e6-97a2-6adddc809c6d.png)

**Comment by adrian-chan-titan** [comment]
fixed

**Comment by ravi-josyula** [comment]
Still issue is not fixed
![2016-05-24_1005](https://cloud.githubusercontent.com/assets/13309806/15492279/2462f6d2-2197-11e6-920f-98fda9b433dd.png)

**Comment by euveng** [comment]
Fixed.
