### ISSUE TITLE
Products & Services  : Content should not cross the boundary of the page

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#76]
![projects - cse global 2016-04-26 11-33-45](https://cloud.githubusercontent.com/assets/13309806/14813092/ba480e66-0bbd-11e6-9044-347576050ac1.png)

**Comment by adrian-chan-titan** [comment]
fixed

**Comment by ravi-josyula** [comment]
Still issue is not fixed as per design
![2016-05-24_0929](https://cloud.githubusercontent.com/assets/13309806/15491835/36c3fb32-2192-11e6-9c2f-92f8b7d410fa.png)

**Comment by euveng** [comment]
Fixed.
